version: '3.3'
services:
  postgres:
    image: "postgres:12.2"
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: kamkodp123
      POSTGRES_USER: kamko-dp
      POSTGRES_DB:
    shm_size: 512mb
