[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"

[api] # traefik api endpoint (at 8080)

[certificatesResolvers.default.acme] # let's encrypt ACME resolver
  email = "j@necek.com"
  storage = "/certs/acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entrypoint = "web"

#[log]
#  level = "DEBUG"
