name: nginx-redirect image

on:
  push:
    paths:
      - 'vps/docker/nginx-redirect/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build image and publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kamko/fiit_masters_thesis_project/nginx-redirect
          username: kamko
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: vps/docker/nginx-redirect
          snapshot: true